name: Deploy on clouds

on:
  push:
    branches:
      - main

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: aws
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn
        env:
          NODE_ENV: development

      - name: Build project
        run: yarn build

      - name: Deploy to AWS with Serverless
        run: yarn deploy:aws

      - name: Run database migration
        run: |
          node ace migration:run --force

  deploy-azure:
    runs-on: windows-latest
    env:
      DB_CONNECTION: azure
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn
        env:
          NODE_ENV: development

      - name: Build project
        run: yarn build

      - name: Deploy to Azure with Serverless
        run: yarn deploy:azure

      - name: Run database migration
        run: |
          node ace migration:run --force

env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  DOMAIN_URL: ${{ secrets.DOMAIN_URL }}

  APP_KEY: ${{ secrets.APP_KEY }}
  APP_NAME: ${{ secrets.APP_NAME }}

  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  HASH_DRIVER: ${{ secrets.HASH_DRIVER }}

  DB_CLIENT: ${{ secrets.DB_CLIENT }}

  DB_AWS_HOST: ${{ secrets.DB_AWS_HOST }}
  DB_AWS_PORT: ${{ secrets.DB_AWS_PORT }}
  DB_AWS_USER: ${{ secrets.DB_AWS_USER }}
  DB_AWS_PASSWORD: ${{ secrets.DB_AWS_PASSWORD }}
  DB_AWS_NAME: ${{ secrets.DB_AWS_NAME }}

  DB_AZURE_HOST: ${{ secrets.DB_AZURE_HOST }}
  DB_AZURE_PORT: ${{ secrets.DB_AZURE_PORT }}
  DB_AZURE_USER: ${{ secrets.DB_AZURE_USER }}
  DB_AZURE_PASSWORD: ${{ secrets.DB_AZURE_PASSWORD }}
  DB_AZURE_NAME: ${{ secrets.DB_AZURE_NAME }}
